// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYomQSb0XL9THlKoz8UUR_ctjNKgjrB1A',
    appId: '1:885842410300:web:dcf434b4a58555f24a7c39',
    messagingSenderId: '885842410300',
    projectId: 'app-truyen-tranh-db2b0',
    authDomain: 'app-truyen-tranh-db2b0.firebaseapp.com',
    storageBucket: 'app-truyen-tranh-db2b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYewZa9DJvM2922MGRuEQ-Uy5L_iDn_hw',
    appId: '1:885842410300:android:57cdb3cc084a9cac4a7c39',
    messagingSenderId: '885842410300',
    projectId: 'app-truyen-tranh-db2b0',
    storageBucket: 'app-truyen-tranh-db2b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdZRGfMzwE1oRyZqSukYEgW_Jz6xuC2b0',
    appId: '1:885842410300:ios:5d04df7bad4dcc404a7c39',
    messagingSenderId: '885842410300',
    projectId: 'app-truyen-tranh-db2b0',
    storageBucket: 'app-truyen-tranh-db2b0.firebasestorage.app',
    iosBundleId: 'com.example.appTruyenTranh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdZRGfMzwE1oRyZqSukYEgW_Jz6xuC2b0',
    appId: '1:885842410300:ios:5d04df7bad4dcc404a7c39',
    messagingSenderId: '885842410300',
    projectId: 'app-truyen-tranh-db2b0',
    storageBucket: 'app-truyen-tranh-db2b0.firebasestorage.app',
    iosBundleId: 'com.example.appTruyenTranh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYomQSb0XL9THlKoz8UUR_ctjNKgjrB1A',
    appId: '1:885842410300:web:11698139ebe612934a7c39',
    messagingSenderId: '885842410300',
    projectId: 'app-truyen-tranh-db2b0',
    authDomain: 'app-truyen-tranh-db2b0.firebaseapp.com',
    storageBucket: 'app-truyen-tranh-db2b0.firebasestorage.app',
  );
}
